import type { Trend } from "./trends-types"

export const mlbCategories = ["Hitting", "Power", "Pitching", "On Base"]

export const mlbTrends: Trend[] = [
  // HOT HITTING
  {
    id: "mlb-1",
    playerName: "Bobby Witt Jr.",
    team: "KC",
    position: "SS",
    type: "hot",
    category: "Hitting",
    headline: "Hit streak: 12 games",
    detail: "Has recorded at least one hit in each of his last 12 games, batting .410 over that span with 7 multi-hit games.",
    streakLength: 12,
    streakLabel: "Last 10 games",
    recentGames: [true, true, true, true, true, true, true, true, true, true],
    statValue: ".410",
    statLabel: "AVG L12",
  },
  {
    id: "mlb-2",
    playerName: "Juan Soto",
    team: "NYM",
    position: "RF",
    type: "hot",
    category: "Hitting",
    headline: "Multi-hit in 6 of last 8",
    detail: "Recording multiple hits with consistency. Has 14 hits in his last 32 at-bats with 4 doubles.",
    streakLength: 6,
    streakLabel: "Last 8 games",
    recentGames: [true, true, false, true, true, true, false, true],
    statValue: ".438",
    statLabel: "AVG L8",
  },
  {
    id: "mlb-3",
    playerName: "Trea Turner",
    team: "PHI",
    position: "SS",
    type: "hot",
    category: "Hitting",
    headline: "Extra-base hit in 5 straight",
    detail: "Has recorded an XBH in each of his last 5 games: 3 doubles, 1 triple, and 2 home runs.",
    streakLength: 5,
    streakLabel: "Last 5 games",
    recentGames: [true, true, true, true, true],
    statValue: "6 XBH",
    statLabel: "Last 5 gms",
  },
  // HOT POWER
  {
    id: "mlb-4",
    playerName: "Aaron Judge",
    team: "NYY",
    position: "RF",
    type: "hot",
    category: "Power",
    headline: "HR in 4 of last 5 games",
    detail: "Mashing everything. 5 HRs in his last 5 games with a .917 SLG and 3 barrels. Exit velo averaging 108.2 mph.",
    streakLength: 4,
    streakLabel: "Last 5 games",
    recentGames: [true, true, false, true, true],
    statValue: "5 HR",
    statLabel: "Last 5 gms",
  },
  {
    id: "mlb-5",
    playerName: "Shohei Ohtani",
    team: "LAD",
    position: "DH",
    type: "hot",
    category: "Power",
    headline: "3 HR in last 4 games",
    detail: "Power surge continues with a 1.050 SLG over his last 4. Also stole 2 bases in that span.",
    streakLength: 3,
    streakLabel: "Last 5 games",
    recentGames: [true, false, true, true, false],
    statValue: "1.050",
    statLabel: "SLG L4",
  },
  {
    id: "mlb-6",
    playerName: "Kyle Schwarber",
    team: "PHI",
    position: "DH",
    type: "hot",
    category: "Power",
    headline: "HR in 3 straight games",
    detail: "4 total home runs in his last 3 games. Pulling the ball at a 52% rate with a 16% barrel rate over the stretch.",
    streakLength: 3,
    streakLabel: "Last 5 games",
    recentGames: [false, false, true, true, true],
    statValue: "4 HR",
    statLabel: "Last 3 gms",
  },
  // HOT PITCHING
  {
    id: "mlb-7",
    playerName: "Zack Wheeler",
    team: "PHI",
    position: "SP",
    type: "hot",
    category: "Pitching",
    headline: "8+ K in 4 straight starts",
    detail: "Dominating hitters with a 35% K rate over his last 4 starts. ERA of 1.82 with a 0.78 WHIP.",
    streakLength: 4,
    streakLabel: "Last 5 starts",
    recentGames: [false, true, true, true, true],
    statValue: "35%",
    statLabel: "K rate L4",
  },
  {
    id: "mlb-8",
    playerName: "Chris Sale",
    team: "ATL",
    position: "SP",
    type: "hot",
    category: "Pitching",
    headline: "QS in 6 of last 7 starts",
    detail: "Consistent excellence: 6+ IP with 3 or fewer runs in nearly every outing. 1.95 ERA over the stretch.",
    streakLength: 6,
    streakLabel: "Last 7 starts",
    recentGames: [true, true, false, true, true, true, true],
    statValue: "1.95",
    statLabel: "ERA L7",
  },
  // HOT ON BASE
  {
    id: "mlb-9",
    playerName: "Freddie Freeman",
    team: "LAD",
    position: "1B",
    type: "hot",
    category: "On Base",
    headline: "Reached base in 15 straight",
    detail: "Has reached base via hit or walk in 15 consecutive games. OBP of .482 over that span.",
    streakLength: 15,
    streakLabel: "Last 10 games",
    recentGames: [true, true, true, true, true, true, true, true, true, true],
    statValue: ".482",
    statLabel: "OBP L15",
  },
  // COLD HITTING
  {
    id: "mlb-10",
    playerName: "Mookie Betts",
    team: "LAD",
    position: "SS",
    type: "cold",
    category: "Hitting",
    headline: "4-for-36 in last 9 games",
    detail: "Deep slump with a .111 average. Chasing at a 35% rate which is well above his season norm of 22%.",
    streakLength: 9,
    streakLabel: "Last 9 games",
    recentGames: [false, false, true, false, false, false, true, false, false],
    statValue: ".111",
    statLabel: "AVG L9",
  },
  {
    id: "mlb-11",
    playerName: "Wander Franco",
    team: "TB",
    position: "SS",
    type: "cold",
    category: "Hitting",
    headline: "Hitless in 4 of last 6",
    detail: "Struggling with a .133 average over his last 6 games. Only 2 hits in 15 at-bats.",
    streakLength: 4,
    streakLabel: "Last 6 games",
    recentGames: [false, true, false, false, true, false],
    statValue: ".133",
    statLabel: "AVG L6",
  },
  // COLD POWER
  {
    id: "mlb-12",
    playerName: "Pete Alonso",
    team: "NYM",
    position: "1B",
    type: "cold",
    category: "Power",
    headline: "0 HR in last 14 games",
    detail: "Power has completely dried up. Zero home runs and only 2 XBH over 14 games. SLG has dropped to .298.",
    streakLength: 14,
    streakLabel: "Last 10 games",
    recentGames: [false, false, false, false, false, false, false, false, false, false],
    statValue: ".298",
    statLabel: "SLG L14",
  },
  // COLD PITCHING
  {
    id: "mlb-13",
    playerName: "Gerrit Cole",
    team: "NYY",
    position: "SP",
    type: "cold",
    category: "Pitching",
    headline: "5+ ER in 3 of last 4 starts",
    detail: "Getting hit hard with a 7.84 ERA over his last 4 starts. Hard-hit rate against of 44%.",
    streakLength: 3,
    streakLabel: "Last 4 starts",
    recentGames: [true, false, true, true],
    statValue: "7.84",
    statLabel: "ERA L4",
  },
  {
    id: "mlb-14",
    playerName: "Marcus Stroman",
    team: "NYM",
    position: "SP",
    type: "cold",
    category: "Pitching",
    headline: "Failed to complete 5 IP in 3 straight",
    detail: "Getting knocked out early. Averaging only 4.0 IP per start with an 8.44 ERA over the last 3 outings.",
    streakLength: 3,
    streakLabel: "Last 5 starts",
    recentGames: [false, false, true, true, true],
    statValue: "8.44",
    statLabel: "ERA L3",
  },
]
