export interface StadiumWeather {
  venue: string
  matchup: string
  gameTime: string
  temp: number
  windSpeed: number
  windDir: "Out" | "In" | "L-R" | "R-L" | "Calm"
  condition: "Sunny" | "Partly Cloudy" | "Cloudy" | "Overcast" | "Roof Closed" | "Drizzle"
  humidity: number
  runsImpact: number
  runsRaw: number
  hrImpact: number
  hrRaw: number
  xbhImpact: number
  xbhRaw: number
  hitsImpact: number
  hitsRaw: number
}

export const stadiumWeatherData: StadiumWeather[] = [
  {
    venue: "Coors Field",
    matchup: "TOR @ COL",
    gameTime: "3:10 PM",
    temp: 94,
    windSpeed: 8,
    windDir: "Out",
    condition: "Sunny",
    humidity: 22,
    runsImpact: 29,
    runsRaw: 2.65,
    hrImpact: 19,
    hrRaw: 0.43,
    xbhImpact: 35,
    xbhRaw: 1.26,
    hitsImpact: 6,
    hitsRaw: 0.68,
  },
  {
    venue: "Progressive Field",
    matchup: "TB @ CLE",
    gameTime: "6:10 PM",
    temp: 91,
    windSpeed: 14,
    windDir: "Out",
    condition: "Sunny",
    humidity: 38,
    runsImpact: 16,
    runsRaw: 1.49,
    hrImpact: 22,
    hrRaw: 0.50,
    xbhImpact: 18,
    xbhRaw: 0.64,
    hitsImpact: 0,
    hitsRaw: 0.00,
  },
  {
    venue: "Great American BP",
    matchup: "CHC @ CIN",
    gameTime: "6:40 PM",
    temp: 90,
    windSpeed: 10,
    windDir: "Out",
    condition: "Partly Cloudy",
    humidity: 42,
    runsImpact: 10,
    runsRaw: 0.91,
    hrImpact: 28,
    hrRaw: 0.63,
    xbhImpact: -6,
    xbhRaw: -0.23,
    hitsImpact: 1,
    hitsRaw: 0.13,
  },
  {
    venue: "Guaranteed Rate Fld",
    matchup: "DET @ CHW",
    gameTime: "7:10 PM",
    temp: 88,
    windSpeed: 12,
    windDir: "L-R",
    condition: "Sunny",
    humidity: 35,
    runsImpact: 6,
    runsRaw: 0.54,
    hrImpact: 18,
    hrRaw: 0.40,
    xbhImpact: -11,
    xbhRaw: -0.40,
    hitsImpact: 4,
    hitsRaw: 0.45,
  },
  {
    venue: "American Family Fld",
    matchup: "PHI @ MIL",
    gameTime: "7:10 PM",
    temp: 86,
    windSpeed: 11,
    windDir: "L-R",
    condition: "Partly Cloudy",
    humidity: 48,
    runsImpact: 6,
    runsRaw: 0.52,
    hrImpact: 22,
    hrRaw: 0.50,
    xbhImpact: -1,
    xbhRaw: -0.05,
    hitsImpact: -3,
    hitsRaw: -0.36,
  },
  {
    venue: "Nationals Park",
    matchup: "MIA @ WAS",
    gameTime: "6:45 PM",
    temp: 92,
    windSpeed: 9,
    windDir: "Out",
    condition: "Sunny",
    humidity: 52,
    runsImpact: 6,
    runsRaw: 0.51,
    hrImpact: 5,
    hrRaw: 0.11,
    xbhImpact: 2,
    xbhRaw: 0.08,
    hitsImpact: 3,
    hitsRaw: 0.35,
  },
  {
    venue: "Kauffman Stadium",
    matchup: "BOS @ KC",
    gameTime: "7:10 PM",
    temp: 89,
    windSpeed: 15,
    windDir: "In",
    condition: "Partly Cloudy",
    humidity: 55,
    runsImpact: 5,
    runsRaw: 0.47,
    hrImpact: -20,
    hrRaw: -0.45,
    xbhImpact: 3,
    xbhRaw: 0.10,
    hitsImpact: 15,
    hitsRaw: 1.60,
  },
  {
    venue: "Chase Field",
    matchup: "BAL @ ARI",
    gameTime: "9:10 PM",
    temp: 78,
    windSpeed: 0,
    windDir: "Calm",
    condition: "Roof Closed",
    humidity: 40,
    runsImpact: 3,
    runsRaw: 0.23,
    hrImpact: -6,
    hrRaw: -0.13,
    xbhImpact: 13,
    xbhRaw: 0.47,
    hitsImpact: 0,
    hitsRaw: -0.05,
  },
  {
    venue: "Dodger Stadium",
    matchup: "ATL @ LAD",
    gameTime: "10:10 PM",
    temp: 82,
    windSpeed: 7,
    windDir: "Out",
    condition: "Sunny",
    humidity: 30,
    runsImpact: 0,
    runsRaw: -0.02,
    hrImpact: 6,
    hrRaw: 0.13,
    xbhImpact: -6,
    xbhRaw: -0.20,
    hitsImpact: 0,
    hitsRaw: -0.02,
  },
  {
    venue: "Busch Stadium",
    matchup: "PIT @ STL",
    gameTime: "7:15 PM",
    temp: 87,
    windSpeed: 10,
    windDir: "In",
    condition: "Partly Cloudy",
    humidity: 60,
    runsImpact: -3,
    runsRaw: -0.25,
    hrImpact: -2,
    hrRaw: -0.05,
    xbhImpact: -7,
    xbhRaw: -0.25,
    hitsImpact: 1,
    hitsRaw: 0.12,
  },
  {
    venue: "Citi Field",
    matchup: "SEA @ NYM",
    gameTime: "7:10 PM",
    temp: 84,
    windSpeed: 12,
    windDir: "Out",
    condition: "Cloudy",
    humidity: 65,
    runsImpact: -5,
    runsRaw: -0.48,
    hrImpact: 7,
    hrRaw: 0.15,
    xbhImpact: -9,
    xbhRaw: -0.32,
    hitsImpact: -7,
    hitsRaw: -0.72,
  },
  {
    venue: "Petco Park",
    matchup: "SF @ SD",
    gameTime: "9:40 PM",
    temp: 72,
    windSpeed: 8,
    windDir: "R-L",
    condition: "Cloudy",
    humidity: 70,
    runsImpact: -6,
    runsRaw: -0.53,
    hrImpact: 9,
    hrRaw: 0.20,
    xbhImpact: -8,
    xbhRaw: -0.28,
    hitsImpact: -8,
    hitsRaw: -0.82,
  },
  {
    venue: "Minute Maid Park",
    matchup: "NYY @ HOU",
    gameTime: "7:10 PM",
    temp: 73,
    windSpeed: 0,
    windDir: "Calm",
    condition: "Roof Closed",
    humidity: 45,
    runsImpact: -6,
    runsRaw: -0.59,
    hrImpact: 5,
    hrRaw: 0.11,
    xbhImpact: -8,
    xbhRaw: -0.28,
    hitsImpact: -6,
    hitsRaw: -0.68,
  },
  {
    venue: "Globe Life Field",
    matchup: "MIN @ TEX",
    gameTime: "8:05 PM",
    temp: 73,
    windSpeed: 0,
    windDir: "Calm",
    condition: "Roof Closed",
    humidity: 42,
    runsImpact: -7,
    runsRaw: -0.61,
    hrImpact: -3,
    hrRaw: -0.06,
    xbhImpact: -15,
    xbhRaw: -0.55,
    hitsImpact: 1,
    hitsRaw: 0.12,
  },
  {
    venue: "Oakland Coliseum",
    matchup: "LAA @ OAK",
    gameTime: "9:40 PM",
    temp: 68,
    windSpeed: 16,
    windDir: "In",
    condition: "Overcast",
    humidity: 75,
    runsImpact: -10,
    runsRaw: -0.88,
    hrImpact: -10,
    hrRaw: -0.22,
    xbhImpact: -6,
    xbhRaw: -0.21,
    hitsImpact: -5,
    hitsRaw: -0.49,
  },
  {
    venue: "Wrigley Field",
    matchup: "CIN @ CHC",
    gameTime: "1:20 PM",
    temp: 85,
    windSpeed: 18,
    windDir: "Out",
    condition: "Sunny",
    humidity: 32,
    runsImpact: 12,
    runsRaw: 1.10,
    hrImpact: 25,
    hrRaw: 0.56,
    xbhImpact: 10,
    xbhRaw: 0.38,
    hitsImpact: 2,
    hitsRaw: 0.22,
  },
]
