import type { Trend } from "./trends-types"

export const nbaCategories = ["Scoring", "Threes", "Rebounds", "Assists"]

export const nbaTrends: Trend[] = [
  // HOT SCORING
  {
    id: "nba-1",
    playerName: "Jayson Tatum",
    team: "BOS",
    position: "SF",
    type: "hot",
    category: "Scoring",
    headline: "30+ points in 6 straight",
    detail: "Averaging 34.8 PPG over his last 6 games on 52% FG and 41% from three. Dominant in the 4th quarter with 9.2 PPG in crunch time.",
    streakLength: 6,
    streakLabel: "Last 8 games",
    recentGames: [true, false, true, true, true, true, true, true],
    statValue: "34.8",
    statLabel: "PPG L6",
  },
  {
    id: "nba-2",
    playerName: "Shai Gilgeous-Alexander",
    team: "OKC",
    position: "PG",
    type: "hot",
    category: "Scoring",
    headline: "25+ in 10 straight games",
    detail: "Has not scored below 25 in over two weeks. 31.2 PPG average with a true shooting of 64.1% over the stretch.",
    streakLength: 10,
    streakLabel: "Last 10 games",
    recentGames: [true, true, true, true, true, true, true, true, true, true],
    statValue: "31.2",
    statLabel: "PPG L10",
  },
  {
    id: "nba-3",
    playerName: "Anthony Edwards",
    team: "MIN",
    position: "SG",
    type: "hot",
    category: "Scoring",
    headline: "28+ in 5 of last 6",
    detail: "Hitting his stride with explosive scoring. 30.4 PPG with 5 games of 28+ and a 40-point outburst in the mix.",
    streakLength: 5,
    streakLabel: "Last 6 games",
    recentGames: [true, true, false, true, true, true],
    statValue: "30.4",
    statLabel: "PPG L6",
  },
  // HOT THREES
  {
    id: "nba-4",
    playerName: "Klay Thompson",
    team: "DAL",
    position: "SG",
    type: "hot",
    category: "Threes",
    headline: "4+ threes in 5 straight",
    detail: "Scorching from deep: 5.2 3PM per game on 47.3% shooting from beyond the arc over his last 5.",
    streakLength: 5,
    streakLabel: "Last 5 games",
    recentGames: [true, true, true, true, true],
    statValue: "5.2",
    statLabel: "3PM/G L5",
  },
  {
    id: "nba-5",
    playerName: "Steph Curry",
    team: "GSW",
    position: "PG",
    type: "hot",
    category: "Threes",
    headline: "5+ threes in 4 of last 6",
    detail: "Vintage Curry: 4.8 3PM per game on 44.6% from three. Had back-to-back 7-three performances.",
    streakLength: 4,
    streakLabel: "Last 6 games",
    recentGames: [true, true, false, true, false, true],
    statValue: "44.6%",
    statLabel: "3P% L6",
  },
  // HOT REBOUNDS
  {
    id: "nba-6",
    playerName: "Domantas Sabonis",
    team: "SAC",
    position: "C",
    type: "hot",
    category: "Rebounds",
    headline: "12+ rebounds in 8 straight",
    detail: "Board monster: averaging 14.6 RPG with 4 games of 15+. Grabbing 5.2 offensive rebounds per game.",
    streakLength: 8,
    streakLabel: "Last 8 games",
    recentGames: [true, true, true, true, true, true, true, true],
    statValue: "14.6",
    statLabel: "RPG L8",
  },
  {
    id: "nba-7",
    playerName: "Victor Wembanyama",
    team: "SAS",
    position: "C",
    type: "hot",
    category: "Rebounds",
    headline: "10+ boards in 7 of last 8",
    detail: "Using his length to dominate the glass. 12.4 RPG with 3.8 blocks per game over the stretch.",
    streakLength: 7,
    streakLabel: "Last 8 games",
    recentGames: [true, true, true, false, true, true, true, true],
    statValue: "12.4",
    statLabel: "RPG L8",
  },
  // HOT ASSISTS
  {
    id: "nba-8",
    playerName: "Tyrese Haliburton",
    team: "IND",
    position: "PG",
    type: "hot",
    category: "Assists",
    headline: "10+ assists in 6 straight",
    detail: "Running the offense at an elite level with 12.3 APG and only 2.1 turnovers per game. AST/TO ratio of 5.9.",
    streakLength: 6,
    streakLabel: "Last 7 games",
    recentGames: [true, true, true, true, true, true, false],
    statValue: "12.3",
    statLabel: "APG L6",
  },
  {
    id: "nba-9",
    playerName: "LaMelo Ball",
    team: "CHA",
    position: "PG",
    type: "hot",
    category: "Assists",
    headline: "8+ assists in 5 of last 6",
    detail: "Facilitating at a high level with 9.8 APG and averaging a near triple-double with 22.4 pts and 7.1 reb.",
    streakLength: 5,
    streakLabel: "Last 6 games",
    recentGames: [true, true, false, true, true, true],
    statValue: "9.8",
    statLabel: "APG L6",
  },
  // COLD SCORING
  {
    id: "nba-10",
    playerName: "Zion Williamson",
    team: "NO",
    position: "PF",
    type: "cold",
    category: "Scoring",
    headline: "Under 18 pts in 5 of last 7",
    detail: "Struggling to find his rhythm. 15.4 PPG on 41% FG with a career-low 48% TS over the stretch.",
    streakLength: 5,
    streakLabel: "Last 7 games",
    recentGames: [true, false, true, true, false, true, true],
    statValue: "15.4",
    statLabel: "PPG L7",
  },
  {
    id: "nba-11",
    playerName: "James Harden",
    team: "LAC",
    position: "PG",
    type: "cold",
    category: "Scoring",
    headline: "Under 15 pts in 4 straight",
    detail: "Can't buy a bucket: 12.5 PPG on 33% FG and 22% from three over the last 4 games.",
    streakLength: 4,
    streakLabel: "Last 6 games",
    recentGames: [false, false, true, true, true, true],
    statValue: "33%",
    statLabel: "FG% L4",
  },
  // COLD THREES
  {
    id: "nba-12",
    playerName: "Desmond Bane",
    team: "MEM",
    position: "SG",
    type: "cold",
    category: "Threes",
    headline: "1-for-22 from three in last 5",
    detail: "Historically cold from deep. Only 4.5% 3P shooting over 5 games despite averaging 4.4 attempts per game.",
    streakLength: 5,
    streakLabel: "Last 5 games",
    recentGames: [false, false, false, false, false],
    statValue: "4.5%",
    statLabel: "3P% L5",
  },
  // COLD REBOUNDS
  {
    id: "nba-13",
    playerName: "Rudy Gobert",
    team: "MIN",
    position: "C",
    type: "cold",
    category: "Rebounds",
    headline: "Under 8 boards in 4 straight",
    detail: "Uncharacteristically low rebounding. 6.5 RPG over the stretch compared to his season average of 12.8.",
    streakLength: 4,
    streakLabel: "Last 5 games",
    recentGames: [false, true, true, true, true],
    statValue: "6.5",
    statLabel: "RPG L4",
  },
]
