import type { Trend } from "./trends-types"

export const nflCategories = ["Passing", "Rushing", "Receiving", "Touchdowns"]

export const nflTrends: Trend[] = [
  // HOT PASSING
  {
    id: "nfl-1",
    playerName: "Josh Allen",
    team: "BUF",
    position: "QB",
    type: "hot",
    category: "Passing",
    headline: "300+ pass yards in 4 straight",
    detail: "Averaging 342.5 pass yards per game with 12 TDs and only 1 INT over the stretch. Completion rate of 71.2%.",
    streakLength: 4,
    streakLabel: "Last 5 games",
    recentGames: [false, true, true, true, true],
    statValue: "342.5",
    statLabel: "Pass YPG L4",
  },
  {
    id: "nfl-2",
    playerName: "Lamar Jackson",
    team: "BAL",
    position: "QB",
    type: "hot",
    category: "Passing",
    headline: "3+ TD passes in 5 of last 6",
    detail: "Dual-threat dominance: 18 passing TDs in 6 games while adding 284 rushing yards. Passer rating of 121.4.",
    streakLength: 5,
    streakLabel: "Last 6 games",
    recentGames: [true, true, false, true, true, true],
    statValue: "121.4",
    statLabel: "Passer Rtg L6",
  },
  // HOT RUSHING
  {
    id: "nfl-3",
    playerName: "Derrick Henry",
    team: "BAL",
    position: "RB",
    type: "hot",
    category: "Rushing",
    headline: "100+ rush yards in 5 straight",
    detail: "Bulldozing defenses with 128.4 YPG on 5.3 YPC. Has 6 rushing TDs over the 5-game stretch.",
    streakLength: 5,
    streakLabel: "Last 5 games",
    recentGames: [true, true, true, true, true],
    statValue: "128.4",
    statLabel: "Rush YPG L5",
  },
  {
    id: "nfl-4",
    playerName: "Saquon Barkley",
    team: "PHI",
    position: "RB",
    type: "hot",
    category: "Rushing",
    headline: "90+ total yards in 7 of last 8",
    detail: "Consistent production: 112.6 total yards per game with 4 rushing TDs and 2 receiving TDs.",
    streakLength: 7,
    streakLabel: "Last 8 games",
    recentGames: [true, true, true, false, true, true, true, true],
    statValue: "112.6",
    statLabel: "Total YPG L8",
  },
  // HOT RECEIVING
  {
    id: "nfl-5",
    playerName: "Ja'Marr Chase",
    team: "CIN",
    position: "WR",
    type: "hot",
    category: "Receiving",
    headline: "100+ rec yards in 4 of last 5",
    detail: "Torching secondaries with 121.8 rec YPG on 8.2 targets per game. 3 TDs over the span.",
    streakLength: 4,
    streakLabel: "Last 5 games",
    recentGames: [true, true, false, true, true],
    statValue: "121.8",
    statLabel: "Rec YPG L5",
  },
  {
    id: "nfl-6",
    playerName: "CeeDee Lamb",
    team: "DAL",
    position: "WR",
    type: "hot",
    category: "Receiving",
    headline: "7+ receptions in 6 straight",
    detail: "Target magnet: 9.3 targets and 8.0 receptions per game. 98.5 YPG with a 86% catch rate.",
    streakLength: 6,
    streakLabel: "Last 6 games",
    recentGames: [true, true, true, true, true, true],
    statValue: "8.0",
    statLabel: "Rec/G L6",
  },
  {
    id: "nfl-7",
    playerName: "Travis Kelce",
    team: "KC",
    position: "TE",
    type: "hot",
    category: "Receiving",
    headline: "70+ rec yards in 5 of last 6",
    detail: "Vintage Kelce production: 84.2 YPG on 6.7 receptions. Still the top TE target in the league.",
    streakLength: 5,
    streakLabel: "Last 6 games",
    recentGames: [true, true, true, false, true, true],
    statValue: "84.2",
    statLabel: "Rec YPG L6",
  },
  // HOT TOUCHDOWNS
  {
    id: "nfl-8",
    playerName: "Bijan Robinson",
    team: "ATL",
    position: "RB",
    type: "hot",
    category: "Touchdowns",
    headline: "TD in 6 straight games",
    detail: "Finding the end zone every week with 8 total TDs (6 rushing, 2 receiving) over his last 6 games.",
    streakLength: 6,
    streakLabel: "Last 7 games",
    recentGames: [false, true, true, true, true, true, true],
    statValue: "8 TD",
    statLabel: "Total TDs L6",
  },
  {
    id: "nfl-9",
    playerName: "Tyreek Hill",
    team: "MIA",
    position: "WR",
    type: "hot",
    category: "Touchdowns",
    headline: "TD in 4 of last 5 games",
    detail: "Big play ability on full display. 4 receiving TDs averaging 28.5 yards per TD reception.",
    streakLength: 4,
    streakLabel: "Last 5 games",
    recentGames: [true, true, true, false, true],
    statValue: "4 TD",
    statLabel: "Rec TDs L5",
  },
  // COLD PASSING
  {
    id: "nfl-10",
    playerName: "Trevor Lawrence",
    team: "JAX",
    position: "QB",
    type: "cold",
    category: "Passing",
    headline: "Under 200 pass yards in 3 of last 4",
    detail: "Struggling with accuracy: 57.8% completion rate with 3 INTs and only 4 TDs. Passer rating of 71.3.",
    streakLength: 3,
    streakLabel: "Last 4 games",
    recentGames: [true, true, false, true],
    statValue: "71.3",
    statLabel: "Passer Rtg L4",
  },
  {
    id: "nfl-11",
    playerName: "Russell Wilson",
    team: "PIT",
    position: "QB",
    type: "cold",
    category: "Passing",
    headline: "2+ INTs in 3 straight games",
    detail: "Turnover prone: 7 interceptions in 3 games. Forcing throws into tight windows with a 42% turnover-worthy play rate.",
    streakLength: 3,
    streakLabel: "Last 5 games",
    recentGames: [false, false, true, true, true],
    statValue: "7 INT",
    statLabel: "Last 3 gms",
  },
  // COLD RUSHING
  {
    id: "nfl-12",
    playerName: "Austin Ekeler",
    team: "WAS",
    position: "RB",
    type: "cold",
    category: "Rushing",
    headline: "Under 40 rush yards in 5 straight",
    detail: "Averaging only 31.2 rush YPG on 3.1 YPC. Losing touches to the backup with only 11.4 carries per game.",
    streakLength: 5,
    streakLabel: "Last 5 games",
    recentGames: [true, true, true, true, true],
    statValue: "31.2",
    statLabel: "Rush YPG L5",
  },
  // COLD RECEIVING
  {
    id: "nfl-13",
    playerName: "Mike Evans",
    team: "TB",
    position: "WR",
    type: "cold",
    category: "Receiving",
    headline: "Under 50 rec yards in 4 of last 5",
    detail: "Quiet stretch: 38.6 rec YPG on only 5.2 targets per game. Zero TDs in the last 5 contests.",
    streakLength: 4,
    streakLabel: "Last 5 games",
    recentGames: [true, true, false, true, true],
    statValue: "38.6",
    statLabel: "Rec YPG L5",
  },
  // COLD TOUCHDOWNS
  {
    id: "nfl-14",
    playerName: "Davante Adams",
    team: "NYJ",
    position: "WR",
    type: "cold",
    category: "Touchdowns",
    headline: "0 TD in last 6 games",
    detail: "Can't find the end zone despite 6.8 targets per game. Last TD was over a month ago. Red zone target share dropped to 8%.",
    streakLength: 6,
    streakLabel: "Last 8 games",
    recentGames: [true, true, false, false, false, false, false, false],
    statValue: "0 TD",
    statLabel: "Last 6 gms",
  },
]
