export interface NrfiPitcher {
  id: string
  time: string
  team: string
  player: string
  hand: "R" | "L"
  record: string
  nrfiPct: number
  streak: number // positive = NRFI streak, negative = RFI streak
  hrsAllowed: number
  opponent: string
  opponentRecord: string
  opponentNrfiStreak: number // positive = NRFI streak, negative = RFI streak
  opponentNrfiRank: number
}

export const nrfiPitchers: NrfiPitcher[] = [
  {
    id: "horton",
    time: "11:20 AM",
    team: "CHC",
    player: "Cade Horton",
    hand: "R",
    record: "15 - 7",
    nrfiPct: 68,
    streak: 2,
    hrsAllowed: 2,
    opponent: "MIL",
    opponentRecord: "125 - 37",
    opponentNrfiStreak: 15,
    opponentNrfiRank: 2,
  },
  {
    id: "peralta",
    time: "11:20 AM",
    team: "MIL",
    player: "Freddy Peralta",
    hand: "R",
    record: "29 - 7",
    nrfiPct: 81,
    streak: 1,
    hrsAllowed: 7,
    opponent: "CHC",
    opponentRecord: "113 - 49",
    opponentNrfiStreak: 5,
    opponentNrfiRank: 18,
  },
  {
    id: "perez",
    time: "3:40 PM",
    team: "MIA",
    player: "Eury Perez",
    hand: "R",
    record: "12 - 8",
    nrfiPct: 60,
    streak: 1,
    hrsAllowed: 6,
    opponent: "STL",
    opponentRecord: "123 - 39",
    opponentNrfiStreak: 4,
    opponentNrfiRank: 3,
  },
  {
    id: "flaherty",
    time: "3:40 PM",
    team: "DET",
    player: "Jack Flaherty",
    hand: "R",
    record: "27 - 6",
    nrfiPct: 82,
    streak: 5,
    hrsAllowed: 4,
    opponent: "HOU",
    opponentRecord: "119 - 43",
    opponentNrfiStreak: -1,
    opponentNrfiRank: 7,
  },
  {
    id: "gausman",
    time: "3:40 PM",
    team: "TOR",
    player: "Kevin Gausman",
    hand: "R",
    record: "26 - 11",
    nrfiPct: 70,
    streak: 1,
    hrsAllowed: 4,
    opponent: "PIT",
    opponentRecord: "115 - 47",
    opponentNrfiStreak: 6,
    opponentNrfiRank: 13,
  },
  {
    id: "liberatore",
    time: "3:40 PM",
    team: "STL",
    player: "Matthew Liberatore",
    hand: "L",
    record: "22 - 7",
    nrfiPct: 76,
    streak: -4,
    hrsAllowed: 4,
    opponent: "MIA",
    opponentRecord: "120 - 42",
    opponentNrfiStreak: 13,
    opponentNrfiRank: 4,
  },
  {
    id: "skenes",
    time: "3:40 PM",
    team: "PIT",
    player: "Paul Skenes",
    hand: "R",
    record: "30 - 2",
    nrfiPct: 94,
    streak: 1,
    hrsAllowed: 2,
    opponent: "TOR",
    opponentRecord: "117 - 45",
    opponentNrfiStreak: -3,
    opponentNrfiRank: 12,
  },
  {
    id: "arrighetti",
    time: "3:40 PM",
    team: "HOU",
    player: "Spencer Arrighetti",
    hand: "R",
    record: "5 - 2",
    nrfiPct: 71,
    streak: 1,
    hrsAllowed: 1,
    opponent: "DET",
    opponentRecord: "120 - 42",
    opponentNrfiStreak: 10,
    opponentNrfiRank: 4,
  },
  {
    id: "gilbert",
    time: "3:45 PM",
    team: "SEA",
    player: "Logan Gilbert",
    hand: "R",
    record: "18 - 10",
    nrfiPct: 64,
    streak: 1,
    hrsAllowed: 4,
    opponent: "PHI",
    opponentRecord: "107 - 55",
    opponentNrfiStreak: 6,
    opponentNrfiRank: -20,
  },
  {
    id: "suarez",
    time: "3:45 PM",
    team: "PHI",
    player: "Ranger Suarez",
    hand: "L",
    record: "23 - 3",
    nrfiPct: 88,
    streak: 2,
    hrsAllowed: 1,
    opponent: "SEA",
    opponentRecord: "114 - 48",
    opponentNrfiStreak: 11,
    opponentNrfiRank: 15,
  },
  {
    id: "may",
    time: "4:10 PM",
    team: "BOS",
    player: "Dustin May",
    hand: "R",
    record: "15 - 8",
    nrfiPct: 65,
    streak: 1,
    hrsAllowed: 3,
    opponent: "BAL",
    opponentRecord: "120 - 42",
    opponentNrfiStreak: 5,
    opponentNrfiRank: 4,
  },
  {
    id: "rogers",
    time: "4:10 PM",
    team: "BAL",
    player: "Trevor Rogers",
    hand: "L",
    record: "16 - 2",
    nrfiPct: 89,
    streak: 1,
    hrsAllowed: 2,
    opponent: "BOS",
    opponentRecord: "111 - 51",
    opponentNrfiStreak: -1,
    opponentNrfiRank: 20,
  },
  {
    id: "strider",
    time: "4:15 PM",
    team: "ATL",
    player: "Spencer Strider",
    hand: "R",
    record: "18 - 5",
    nrfiPct: 78,
    streak: -3,
    hrsAllowed: 2,
    opponent: "CWS",
    opponentRecord: "111 - 51",
    opponentNrfiStreak: -1,
    opponentNrfiRank: 20,
  },
  {
    id: "gomez",
    time: "4:15 PM",
    team: "CWS",
    player: "Yoandrys Gomez",
    hand: "R",
    record: "6 - 3",
    nrfiPct: 67,
    streak: 1,
    hrsAllowed: 1,
    opponent: "ATL",
    opponentRecord: "114 - 48",
    opponentNrfiStreak: -1,
    opponentNrfiRank: 15,
  },
  {
    id: "leiter",
    time: "4:40 PM",
    team: "TEX",
    player: "Jack Leiter",
    hand: "R",
    record: "21 - 8",
    nrfiPct: 72,
    streak: 1,
    hrsAllowed: 3,
    opponent: "KC",
    opponentRecord: "110 - 52",
    opponentNrfiStreak: -1,
    opponentNrfiRank: 23,
  },
  {
    id: "wacha",
    time: "4:40 PM",
    team: "KC",
    player: "Michael Wacha",
    hand: "R",
    record: "27 - 4",
    nrfiPct: 87,
    streak: 2,
    hrsAllowed: 1,
    opponent: "TEX",
    opponentRecord: "119 - 43",
    opponentNrfiStreak: 1,
    opponentNrfiRank: 7,
  },
  {
    id: "freeland",
    time: "5:40 PM",
    team: "COL",
    player: "Kyle Freeland",
    hand: "L",
    record: "17 - 14",
    nrfiPct: 55,
    streak: 1,
    hrsAllowed: 11,
    opponent: "LAD",
    opponentRecord: "109 - 53",
    opponentNrfiStreak: 17,
    opponentNrfiRank: -25,
  },
  {
    id: "yamamoto",
    time: "5:40 PM",
    team: "LAD",
    player: "Yoshinobu Yamamoto",
    hand: "R",
    record: "25 - 10",
    nrfiPct: 71,
    streak: 2,
    hrsAllowed: 4,
    opponent: "COL",
    opponentRecord: "128 - 34",
    opponentNrfiStreak: 1,
    opponentNrfiRank: -1,
  },
]

export function getStreakColor(streak: number): string {
  if (streak >= 5) return "bg-emerald-500/20 text-emerald-400 border border-emerald-500/30"
  if (streak >= 3) return "bg-emerald-500/10 text-emerald-400"
  if (streak <= -5) return "bg-red-500/20 text-red-400 border border-red-500/30"
  if (streak <= -3) return "bg-red-500/10 text-red-400"
  return "text-muted-foreground"
}

export function getRankColor(rank: number): string {
  if (rank <= 3 && rank > 0) return "bg-emerald-500 text-white"
  if (rank <= 8 && rank > 0) return "bg-emerald-500/20 text-emerald-400"
  if (rank < 0 || rank >= 20) return "bg-red-500 text-white"
  if (rank >= 15) return "bg-red-500/20 text-red-400"
  return "text-muted-foreground"
}

export function getNrfiPctColor(pct: number): string {
  if (pct >= 85) return "text-emerald-400"
  if (pct >= 75) return "text-emerald-400/80"
  if (pct <= 55) return "text-red-400"
  if (pct <= 65) return "text-amber-400"
  return "text-foreground"
}
